name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Test
        # Not to use "make autograde" because it's for grading purpose and the recipe ignores errors.
        run: ARGS="make test" make activate
